# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-13 14:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
    ]
