# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-23 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onegeo_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analyzer',
            name='filter',
        ),
        migrations.RemoveField(
            model_name='analyzer',
            name='tokenizer',
        ),
        migrations.RemoveField(
            model_name='analyzer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='filter',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tokenizer',
            name='user',
        ),
        migrations.AlterField(
            model_name='searchmodel',
            name='name',
            field=models.CharField(max_length=250, unique=True, verbose_name='Name'),
        ),
        migrations.DeleteModel(
            name='Analyzer',
        ),
        migrations.DeleteModel(
            name='Filter',
        ),
        migrations.DeleteModel(
            name='Tokenizer',
        ),
    ]
