# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-25 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onegeo_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexprofile',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='searchmodel',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='source',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Name'),
        ),
    ]
