# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-01 10:14
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('onegeo_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analyzer',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Name')),
                ('config', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Config')),
                ('reserved', models.BooleanField(default=False, verbose_name='Reserved')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Name')),
                ('config', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Config')),
                ('reserved', models.BooleanField(default=False, verbose_name='Reserved')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RelatedFilters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analyzer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onegeo_api.Analyzer')),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onegeo_api.Filter')),
            ],
        ),
        migrations.CreateModel(
            name='Tokenizer',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Name')),
                ('config', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Config')),
                ('reserved', models.BooleanField(default=False, verbose_name='Reserved')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='analyzer',
            name='filters',
            field=models.ManyToManyField(blank=True, through='onegeo_api.RelatedFilters', to='onegeo_api.Filter'),
        ),
        migrations.AddField(
            model_name='analyzer',
            name='tokenizer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='onegeo_api.Tokenizer'),
        ),
        migrations.AddField(
            model_name='analyzer',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
