# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-07 10:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onegeo_api', '0002_remove_context_resources'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContextResourceMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onegeo_api.Context')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onegeo_api.Resource')),
            ],
        ),
        migrations.AddField(
            model_name='context',
            name='resources',
            field=models.ManyToManyField(through='onegeo_api.ContextResourceMap', to='onegeo_api.Resource'),
        ),
        migrations.AlterUniqueTogether(
            name='contextresourcemap',
            unique_together=set([('resource', 'context')]),
        ),
    ]
