# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-07 13:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onegeo_api', '0004_remove_context_resources'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contextresourcemap',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='contextresourcemap',
            name='context',
        ),
        migrations.RemoveField(
            model_name='contextresourcemap',
            name='resource',
        ),
        migrations.DeleteModel(
            name='ContextResourceMap',
        ),
    ]
