# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-07 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onegeo_api', '0005_auto_20171107_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='context',
            name='resources',
            field=models.ManyToManyField(to='onegeo_api.Resource'),
        ),
    ]
